# Render Blueprint configuration
services:
  - type: web
    name: hrone-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB_NAME
        value: hrone
    healthCheckPath: /health